SELECT
    AI.AUTHOR_ID AS AUTHOR_ID
    , AI.AUTHOR_NAME AS AUTHOR_NAME
    , BK.CATEGORY AS CATEGORY
    , SUM(BK.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK BK
INNER JOIN AUTHOR AI
ON BK.AUTHOR_ID = AI.AUTHOR_ID
INNER JOIN(
    SELECT
        BOOK_ID
       , SALES
    FROM BOOK_SALES 
    WHERE TO_CHAR(SALES_DATE,'YYYYMM') = '202201'
) BS
ON BK.BOOK_ID = BS.BOOK_ID
GROUP BY  AI.AUTHOR_ID, AI.AUTHOR_NAME, BK.CATEGORY 
ORDER BY AI.AUTHOR_ID ASC, BK.CATEGORY DESC







    