SELECT 
    T1.AUTHOR_ID
    , T1.AUTHOR_NAME
    , T1.CATEGORY
    , SUM(T1.INDV_SALES) AS TOTAL_SALES
FROM(
    SELECT 
        B.AUTHOR_ID
        , A.AUTHOR_NAME
        , B.CATEGORY
        , (B.PRICE * BS.SALES) AS INDV_SALES
    FROM(
        SELECT
            BOOK_ID
            , SALES
        FROM 
            BOOK_SALES
        WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
    )BS
    INNER JOIN(
        SELECT
            BOOK_ID
            , CATEGORY
            , AUTHOR_ID
            , PRICE
        FROM BOOK 
    )B
    ON BS.BOOK_ID = B.BOOK_ID
    INNER JOIN AUTHOR A
    ON A.AUTHOR_ID = B.AUTHOR_ID
)T1
GROUP BY T1.CATEGORY, T1.AUTHOR_ID, T1.AUTHOR_NAME
ORDER BY T1.AUTHOR_ID ASC, T1.CATEGORY DESC
