SELECT
    DISTINCT CP.CART_ID AS CART_ID
FROM
    CART_PRODUCTS CP
INNER JOIN (
    SELECT
        CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)T1
ON CP.CART_ID=T1.CART_ID
INNER JOIN (
    SELECT
        CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)T2
ON CP.CART_ID=T2.CART_ID
ORDER BY CP.CART_ID