-- 코드를 입력하세요
SELECT
   T1.SALES_DATE AS SALES_DATE
   ,T1.PRODUCT_ID AS PRODUCT_ID
   , NVL(TO_CHAR(T1.USER_ID) , NULL) AS USER_ID
   , T1.SALES_AMOUNT AS SALES_AMOUNT
    FROM(
        SELECT
             TO_CHAR(OFS.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,
             OFS.PRODUCT_ID AS PRODUCT_ID
             , NULL AS USER_ID
             , OFS.SALES_AMOUNT AS SALES_AMOUNT
        FROM OFFLINE_SALE   OFS
            UNION 
        SELECT
             TO_CHAR(OS.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE
             ,OS.PRODUCT_ID AS PRODUCT_ID
             , OS.USER_ID AS USER_ID
             , OS.SALES_AMOUNT AS SALES_AMOUNT
    FROM ONLINE_SALE   OS
)T1
WHERE T1.SALES_DATE LIKE '%2022-03%'
ORDER BY T1.SALES_DATE ASC, T1.PRODUCT_ID ASC