SELECT  
    CRC.CAR_ID AS CAR_ID,
    CRC.CAR_TYPE AS CAR_TYPE,
    (CRC.DAILY_FEE * 30) * (1 - CRDP.DISCOUNT_RATE / 100) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR CRC
INNER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRDP ON CRC.CAR_TYPE = CRDP.CAR_TYPE
WHERE 
    CRC.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
        WHERE 
            CRH.CAR_ID = CRC.CAR_ID
            AND CRH.START_DATE <= DATE '2022-11-30'
            AND CRH.END_DATE >= DATE '2022-11-01'
    )
    AND CRDP.DURATION_TYPE = '30일 이상'
    AND (CRC.DAILY_FEE * 30) >= 500000
    AND (CRC.DAILY_FEE * 30) < 2000000
ORDER BY 
    FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
