WITH CalculatedFees AS (
    SELECT CRCH.HISTORY_ID, 
           SUM(CRC.DAILY_FEE * (TRUNC(CRCH.END_DATE) - TRUNC(CRCH.START_DATE) + 1) * (100 - NVL(CRCDP.DISCOUNT_RATE, 0)) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR CRC
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCH ON CRC.CAR_ID = CRCH.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP 
         ON CRC.CAR_TYPE = CRCDP.CAR_TYPE
         AND CASE 
                WHEN TRUNC(CRCH.END_DATE) - TRUNC(CRCH.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN TRUNC(CRCH.END_DATE) - TRUNC(CRCH.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN TRUNC(CRCH.END_DATE) - TRUNC(CRCH.START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE NULL
            END = CRCDP.DURATION_TYPE
    WHERE CRC.CAR_TYPE = '트럭'
    GROUP BY CRCH.HISTORY_ID
)
SELECT *
FROM CalculatedFees
ORDER BY FEE DESC, HISTORY_ID DESC;
