SELECT 
    T1.FLAVOR
FROM(
    SELECT
        F.FLAVOR
        , SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TTL_ORDER
    FROM 
        FIRST_HALF F
    INNER JOIN  JULY J
     ON F.FLAVOR = J.FLAVOR
    GROUP BY  F.FLAVOR
     ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
)T1
WHERE ROWNUM BETWEEN 1 AND 3

