WITH TIME AS (
   SELECT LEVEL - 1 AS HOUR 
   FROM DUAL
   CONNECT BY LEVEL - 1 <= 23
)
SELECT 
    T.HOUR AS HOUR,
    NVL(T2.COUNT, 0) AS COUNT
FROM
    TIME T
LEFT JOIN (
    SELECT 
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
        COUNT(*) AS COUNT
    FROM 
        ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
) T2
ON T.HOUR = T2.HOUR
ORDER BY T.HOUR ASC;
