SELECT 
    UGU.USER_ID AS USER_ID
    , UGU.NICKNAME
    , T1.TOTAL_SALES
FROM(
    SELECT
        WRITER_ID
        , SUM(PRICE) AS TOTAL_SALES
    FROM 
        USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)T1
INNER JOIN 
    USED_GOODS_USER UGU
ON T1.WRITER_ID = UGU.USER_ID
ORDER BY T1.TOTAL_SALES ASC