-- 코드를 입력하세요
SELECT * FROM (
    SELECT
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
        , COUNT(*) AS COUNT
    FROM
      ANIMAL_OUTS 
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) 
)T1 
WHERE T1.HOUR BETWEEN 9 AND 19
ORDER BY T1.HOUR

