WITH MAX_COUNT AS (
    SELECT
        MEMBER_ID
        , COUNT(*)
    FROM REST_REVIEW
        GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT
             MAX(COUNT(*))
        FROM
            REST_REVIEW
        GROUP BY MEMBER_ID
    )
)

SELECT
    MP. MEMBER_NAME AS MEMBER_NAME
    , RR.REVIEW_TEXT AS REVIEW_TEXT
    , RR.REVIEW_DATE AS REVIEW_DATE
FROM
     MAX_COUNT MC
INNER JOIN (
    SELECT
        MEMBER_ID
        , MEMBER_NAME
    FROM MEMBER_PROFILE
) MP
ON MC.MEMBER_ID= MP.MEMBER_ID
INNER JOIN(
    SELECT
        MEMBER_ID
        ,  REVIEW_TEXT
        , TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
    FROM 
        REST_REVIEW 
) RR
ON MC.MEMBER_ID = RR.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC







