
SELECT  
    MP.MEMBER_NAME
    , RR.REVIEW_TEXT
    , RR.REVIEW_DATE
FROM(
    SELECT
       MEMBER_ID
    FROM
        REST_REVIEW  RV
    GROUP BY MEMBER_ID
    HAVING  COUNT(*) = (
        SELECT
           MAX(COUNT(*))
        FROM
            REST_REVIEW  RV
        GROUP BY MEMBER_ID
    )
)T1
INNER JOIN (
    SELECT 
        MEMBER_ID
    , MEMBER_NAME
    FROM MEMBER_PROFILE 
)MP
ON T1.MEMBER_ID = MP.MEMBER_ID
INNER JOIN(
    SELECT
        REVIEW_TEXT
        , TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
        , MEMBER_ID
    FROM
        REST_REVIEW 
)RR
ON RR.MEMBER_ID = T1.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC