SELECT
    AI.ANIMAL_ID
    , AI.NAME
FROM
    ANIMAL_INS AI
INNER JOIN(
    SELECT
        ANIMAL_ID
    , DATETIME
    FROM
        ANIMAL_OUTS
)AO
ON 
    AO.DATETIME  < AI.DATETIME
AND
    AO.ANIMAL_ID = AI.ANIMAL_ID
ORDER BY AI.DATETIME ASC