SELECT 
    T1.MONTH,
    T1.CAR_ID,
    COUNT(*) AS RECORDS
FROM (
    SELECT
        TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH,
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (
        SELECT
            CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_NUMBER(TO_CHAR(START_DATE, 'YYYYMM')) BETWEEN 202208 AND 202210
        GROUP BY CAR_ID
        HAVING COUNT(HISTORY_ID) >= 5
    ) 
) T1
WHERE T1.MONTH BETWEEN 08 AND 10
GROUP BY T1.MONTH, T1.CAR_ID
ORDER BY T1.MONTH ASC, T1.CAR_ID DESC;
