SELECT
    HD.DEPT_ID AS DEPT_ID
    , HD.DEPT_NAME_EN AS DEPT_NAME_EN
    , HE.AVG_SAL AS AVG_SAL
FROM
    HR_DEPARTMENT HD
INNER JOIN(
        SELECT
            DEPT_ID
            , ROUND(AVG(SAL),0) AS AVG_SAL
        FROM 
            HR_EMPLOYEES
        GROUP BY DEPT_ID
    )HE
ON HD.DEPT_ID = HE.DEPT_ID
ORDER BY HE.AVG_SAL DESC
;