-- 코드를 입력하세요
SELECT
    B.BOOK_ID
    , AU.AUTHOR_NAME
    , TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD')
FROM
    BOOK B
INNER JOIN AUTHOR AU
ON CATEGORY = '경제'
AND B. AUTHOR_ID = AU. AUTHOR_ID
ORDER BY TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD')